# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ced6c910b56e6bfd01dbd2b031c7323b9a01a7c7995a12eea581a670e178148803736a22e503559ca438fd42ba5cd0fdd5d6ae002a79dfe615e40b531ddbee5e

test:
  secret_key_base: c88185bbaa8419595693fb8b03f2400a280e5b020ff118628ca114a8511e0b13b5e5d8fb26a19047f40f6f0a3ae11e58dc5092f1b45edb8a848114ade85145dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
